### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by jibbo** [nicolaperantoni/Reminiscence#6]
In portrait la timeline si ferma agli anni al 1990.

**Comment by forna1991** [comment]
Sembra che portando la data al 2013 in portrait, girando l'app in landscape, portare la timeline al 1940 e rigirare in portrait replichi questo bug

**Comment by jibbo** [comment]
Penso che sia collegato al fatto dello sliding menu che si rompe. (issue #7)

**Comment by jibbo** [comment]
No, a quanto pare non e' legata al bug #7 .

**Comment by jibbo** [comment]
fixed with  commit 32bd1474c48586ca8cac6ec1f37a738eba9a8b1c
